# Generated by Django 3.1.3 on 2020-11-20 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201119_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
    ]
