# Generated by Django 3.1.3 on 2020-11-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20201120_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='opened',
            field=models.BooleanField(default=True),
        ),
    ]
